import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("sigma bussi is joever L");
      System.out.println("Skibidi aura tweaking twin");
      System.out.println("Rizz fire rage-baiting caught in 4K");
      System.out.println("goofy ahh GOAT moged W");
      System.out.println("Zesty drip washed frfr");
      System.out.println("Omega fire touching grass bruh");
      System.out.println("Omega aura tweaking no shit");
      System.out.println("Skibidi aura looksmaxxing W");
      System.out.println("Rizz aura slapsno cap");
      System.out.println("Omega GOAT sus no shit");
      System.out.println("bussin' bussi SDIYBTing ratio");
      System.out.println("goofy ahh gyatt simp L");
      System.out.println("Skibidi 67 touching grass W");
      System.out.println("Gigachad aura rage-baiting bruh");
      System.out.println("Skibidi gyatt jestermaxxing no shit");
      System.out.println("UWU drip tweaking no cap");
      System.out.println("sigma 67 washed twin");
      System.out.println("Omega fire jestermaxxing KYS");
      System.out.println("Omega gyatt washed cooked");
      System.out.println("sigma aura jestermaxxing cooked");
      System.out.println("Omega fire gooning ratio");
      System.out.println("Gigachad dih SDIYBTing bruh");
      System.out.println("goofy ahh balls washed frfr");
      System.out.println("Zesty sussy baka looksmaxxing cooked");
      System.out.println("bussin' sussy baka looksmaxxing KYS");
      System.out.println("goofy ahh fire touching grass W");
      System.out.println("Rizz toliet slapsKYS");
      System.out.println("Omega drip looksmaxxing no shit");
      System.out.println("sigma drip SDIYBTing W");
      System.out.println("Skibidi 67 slapscaught in 4K");
      System.out.println("Omega toliet gooning frfr");
      System.out.println("bussin' dih slapsL");
      System.out.println("SYBAU fire simp W");
      System.out.println("bussin' sussy baka sus twin");
      System.out.println("UWU sussy baka rage-baiting frfr");
      System.out.println("sigma 67 tweaking L");
      System.out.println("sigma gyatt simp caught in 4K");
      System.out.println("UWU fire jestermaxxing bruh");
      System.out.println("goofy ahh gyatt  lowkirksixsevenuinely moged ratio");
      System.out.println("Cringe sussy baka locked in moged ");
      System.out.println("Omega drip locked in no shit");
      System.out.println("Omega drip be yappin' caught in 4K");
      System.out.println("goofy ahh gyatt touching grass cooked");
      System.out.println("Rizz gyatt simp moged ");
      System.out.println("SYBAU dih slapsno cap");
      System.out.println("Rizz dih moged KYS");
      System.out.println("Gigachad bussi is joever cooked");
      System.out.println("Cringe sussy baka rage-baiting ratio");
      System.out.println("Rizz dih looksmaxxing moged ");
      System.out.println("Skibidi gyatt washed W");
      System.out.println("Omega GOAT locked in moged ");
      System.out.println("Omega dih  lowkirksixsevenuinely moged cooked");
      System.out.println("Gigachad dih  lowkirksixsevenuinely moged twin");
      System.out.println("SYBAU aura touching grass caught in 4K");
      System.out.println("SYBAU 67 fanum taxed cooked");
      System.out.println("goofy ahh drip jestermaxxing L");
      System.out.println("Zesty sussy baka tweaking no cap");
      System.out.println("Skibidi 67 be yappin' moged ");
      System.out.println("Omega dih rage-baiting cooked");
      System.out.println("bussin' dih touching grass W");
      System.out.println("SYBAU aura be yappin' ratio");
      System.out.println("bussin' toliet slapsbruh");
      System.out.println("goofy ahh dih SDIYBTing L");
      System.out.println("Omega fire touching grass no cap");
      System.out.println("goofy ahh gyatt simp twin");
      System.out.println("Zesty GOAT slapsKYS");
      System.out.println("Gigachad dih jestermaxxing caught in 4K");
      System.out.println("Omega balls locked in W");
      System.out.println("SYBAU aura tweaking caught in 4K");
      System.out.println("bussin' GOAT vibe check L");
      System.out.println("Gigachad GOAT SDIYBTing cooked");
      System.out.println("Rizz 67 moged frfr");
      System.out.println("goofy ahh fire locked in L");
      System.out.println("Zesty 67 simp caught in 4K");
      System.out.println("Zesty fire tweaking L");
      System.out.println("sigma dih touching grass ratio");
      System.out.println("bussin' dih simp cooked");
      System.out.println("UWU 67 gooning cooked");
      System.out.println("SYBAU 67 vibe check KYS");
      System.out.println("Skibidi gyatt vibe check L");
      System.out.println("Gigachad dih is joever moged ");
      System.out.println("bussin' 67 slapsfrfr");
      System.out.println("sigma fire simp no cap");
      System.out.println("Rizz bussi locked in bruh");
      System.out.println("Zesty gyatt tweaking caught in 4K");
      System.out.println("goofy ahh gyatt moged no cap");
      System.out.println("Skibidi toliet simp W");
      System.out.println("bussin' gyatt tweaking ratio");
      System.out.println("Zesty sussy baka SDIYBTing L");
      System.out.println("Zesty GOAT sus frfr");
      System.out.println("Gigachad drip is joever cooked");
      System.out.println("goofy ahh bussi washed no shit");
      System.out.println("UWU aura touching grass KYS");
      System.out.println("sigma drip rage-baiting cooked");
      System.out.println("UWU toliet is joever twin");
      System.out.println("Cringe sussy baka looksmaxxing caught in 4K");
      System.out.println("UWU bussi looksmaxxing bruh");
      System.out.println("SYBAU dih vibe check no cap");
      System.out.println("Skibidi 67 slapsno shit");
      System.out.println("Rizz sussy baka gooning moged ");
      System.out.println("Omega toliet locked in ratio");
  }
}