import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("SYBAU toliet be yappin' moged ");
      System.out.println("bussin' sussy baka gooning cooked");
      System.out.println("Cringe fire looksmaxxing bruh");
      System.out.println("SYBAU fire vibe check bruh");
      System.out.println("Omega gyatt vibe check no shit");
      System.out.println("Gigachad GOAT rage-baiting cooked");
      System.out.println("Rizz fire moged moged ");
      System.out.println("Cringe toliet jestermaxxing W");
      System.out.println("Skibidi bussi slapsbruh");
      System.out.println("Omega sussy baka washed bruh");
      System.out.println("Zesty sussy baka  lowkirksixsevenuinely moged L");
      System.out.println("sigma aura vibe check KYS");
      System.out.println("Cringe fire locked in W");
      System.out.println("goofy ahh 67 be yappin' cooked");
      System.out.println("Gigachad 67  lowkirksixsevenuinely moged no shit");
      System.out.println("Rizz balls washed L");
      System.out.println("sigma sussy baka locked in moged ");
      System.out.println("Skibidi drip jestermaxxing caught in 4K");
      System.out.println("SYBAU GOAT jestermaxxing caught in 4K");
      System.out.println("UWU balls touching grass frfr");
      System.out.println("Rizz sussy baka washed W");
      System.out.println("Cringe aura slapsL");
      System.out.println("Rizz 67 is joever moged ");
      System.out.println("UWU fire gooning L");
      System.out.println("goofy ahh toliet is joever moged ");
      System.out.println("UWU gyatt gooning caught in 4K");
      System.out.println("Omega drip fanum taxed twin");
      System.out.println("sigma fire washed ratio");
      System.out.println("Gigachad fire is joever W");
      System.out.println("UWU GOAT fanum taxed cooked");
      System.out.println("goofy ahh fire  lowkirksixsevenuinely moged caught in 4K");
      System.out.println("Omega dih touching grass ratio");
      System.out.println("SYBAU fire  lowkirksixsevenuinely moged cooked");
      System.out.println("UWU dih  lowkirksixsevenuinely moged caught in 4K");
      System.out.println("SYBAU gyatt SDIYBTing bruh");
      System.out.println("Rizz fire is joever bruh");
      System.out.println("Gigachad drip locked in KYS");
      System.out.println("Omega sussy baka locked in twin");
      System.out.println("Omega 67 gooning moged ");
      System.out.println("sigma fire looksmaxxing cooked");
      System.out.println("Zesty 67 fanum taxed frfr");
      System.out.println("bussin' drip simp no shit");
      System.out.println("Gigachad balls sus moged ");
      System.out.println("bussin' 67  lowkirksixsevenuinely moged ratio");
      System.out.println("SYBAU fire vibe check frfr");
      System.out.println("bussin' sussy baka touching grass ratio");
      System.out.println("goofy ahh GOAT SDIYBTing W");
      System.out.println("Zesty bussi washed caught in 4K");
      System.out.println("bussin' balls SDIYBTing no cap");
      System.out.println("SYBAU toliet tweaking caught in 4K");
      System.out.println("goofy ahh dih SDIYBTing caught in 4K");
      System.out.println("Gigachad aura locked in L");
      System.out.println("goofy ahh 67 fanum taxed frfr");
      System.out.println("SYBAU aura gooning W");
      System.out.println("Omega gyatt slapsratio");
      System.out.println("Gigachad bussi locked in L");
      System.out.println("Gigachad 67 fanum taxed no cap");
      System.out.println("sigma bussi jestermaxxing no cap");
      System.out.println("bussin' toliet touching grass no cap");
      System.out.println("Gigachad sussy baka be yappin' cooked");
      System.out.println("bussin' bussi vibe check no shit");
      System.out.println("Zesty balls moged caught in 4K");
      System.out.println("goofy ahh balls tweaking moged ");
      System.out.println("sigma dih locked in caught in 4K");
      System.out.println("bussin' balls be yappin' no shit");
      System.out.println("Rizz bussi is joever L");
      System.out.println("Zesty aura vibe check frfr");
      System.out.println("UWU fire looksmaxxing no cap");
      System.out.println("Zesty toliet jestermaxxing moged ");
      System.out.println("goofy ahh gyatt fanum taxed W");
      System.out.println("goofy ahh gyatt locked in KYS");
      System.out.println("SYBAU bussi fanum taxed no cap");
      System.out.println("bussin' 67 washed W");
      System.out.println("sigma bussi vibe check bruh");
      System.out.println("bussin' fire is joever ratio");
      System.out.println("Zesty toliet SDIYBTing twin");
      System.out.println("goofy ahh gyatt slapscooked");
      System.out.println("UWU 67 touching grass no cap");
      System.out.println("Rizz drip is joever W");
      System.out.println("Zesty dih is joever KYS");
      System.out.println("Omega drip tweaking cooked");
      System.out.println("Gigachad balls sus W");
      System.out.println("UWU bussi washed ratio");
      System.out.println("bussin' aura  lowkirksixsevenuinely moged no cap");
      System.out.println("Rizz bussi SDIYBTing twin");
      System.out.println("UWU bussi is joever no cap");
      System.out.println("sigma balls  lowkirksixsevenuinely moged KYS");
      System.out.println("Skibidi dih vibe check ratio");
      System.out.println("Rizz fire tweaking bruh");
      System.out.println("Cringe sussy baka vibe check no shit");
      System.out.println("Skibidi drip is joever frfr");
      System.out.println("sigma aura tweaking frfr");
      System.out.println("bussin' fire SDIYBTing ratio");
      System.out.println("sigma dih tweaking ratio");
  }
}