import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class rbq{
    public static void main() {
      System.out.println("UWU toliet be yappin' caught in 4K");
      System.out.println("bussin' toliet be yappin' frfr");
      System.out.println("Cringe toliet rage-baiting L");
      System.out.println("Cringe fire looksmaxxing bruh");
      System.out.println("Rizz dih fanum taxed moged ");
      System.out.println("Rizz sussy baka rage-baiting KYS");
      System.out.println("Cringe balls sus L");
      System.out.println("Zesty sussy baka  lowkirksixsevenuinely moged KYS");
      System.out.println("Gigachad sussy baka SDIYBTing twin");
      System.out.println("Rizz toliet SDIYBTing no cap");
      System.out.println("Skibidi fire  lowkirksixsevenuinely moged no cap");
      System.out.println("goofy ahh fire be yappin' KYS");
      System.out.println("sigma gyatt rage-baiting twin");
      System.out.println("Skibidi toliet looksmaxxing twin");
      System.out.println("sigma balls locked in caught in 4K");
      System.out.println("bussin' 67 locked in no shit");
      System.out.println("sigma 67 looksmaxxing moged ");
      System.out.println("bussin' 67 fanum taxed twin");
      System.out.println("Cringe fire vibe check ratio");
      System.out.println("SYBAU bussi jestermaxxing twin");
      System.out.println("bussin' balls tweaking cooked");
      System.out.println("Cringe toliet looksmaxxing moged ");
      System.out.println("Omega sussy baka is joever frfr");
      System.out.println("sigma dih is joever no shit");
      System.out.println("Gigachad gyatt slapsratio");
      System.out.println("UWU bussi looksmaxxing bruh");
      System.out.println("bussin' balls tweaking KYS");
      System.out.println("Skibidi aura sus twin");
      System.out.println("sigma toliet touching grass no cap");
      System.out.println("SYBAU balls SDIYBTing no cap");
      System.out.println("goofy ahh 67 jestermaxxing ratio");
      System.out.println("SYBAU dih simp W");
      System.out.println("sigma drip gooning no cap");
      System.out.println("Rizz aura  lowkirksixsevenuinely moged L");
      System.out.println("Skibidi dih sus cooked");
      System.out.println("UWU gyatt fanum taxed caught in 4K");
      System.out.println("SYBAU dih jestermaxxing bruh");
      System.out.println("Gigachad aura gooning KYS");
      System.out.println("Skibidi aura slapstwin");
      System.out.println("SYBAU aura sus frfr");
      System.out.println("Gigachad dih touching grass frfr");
      System.out.println("sigma sussy baka  lowkirksixsevenuinely moged KYS");
      System.out.println("bussin' fire moged W");
      System.out.println("sigma 67 locked in KYS");
      System.out.println("Cringe balls looksmaxxing cooked");
      System.out.println("Cringe sussy baka  lowkirksixsevenuinely moged L");
      System.out.println("SYBAU 67 simp ratio");
      System.out.println("UWU fire tweaking twin");
      System.out.println("bussin' 67 be yappin' frfr");
      System.out.println("Rizz 67 moged bruh");
      System.out.println("bussin' drip sus cooked");
      System.out.println("sigma 67 rage-baiting moged ");
      System.out.println("Rizz gyatt sus no cap");
      System.out.println("Gigachad bussi moged no cap");
      System.out.println("sigma bussi jestermaxxing moged ");
      System.out.println("UWU dih vibe check twin");
      System.out.println("bussin' fire simp frfr");
      System.out.println("goofy ahh gyatt  lowkirksixsevenuinely moged no shit");
      System.out.println("Zesty 67 SDIYBTing frfr");
      System.out.println("Skibidi GOAT washed ratio");
      System.out.println("Rizz GOAT moged no shit");
      System.out.println("sigma aura locked in L");
      System.out.println("bussin' toliet slapsno cap");
      System.out.println("bussin' gyatt touching grass no shit");
      System.out.println("Cringe 67 locked in no cap");
      System.out.println("goofy ahh toliet sus W");
      System.out.println("bussin' GOAT vibe check no shit");
      System.out.println("Rizz 67 slapsW");
      System.out.println("Cringe GOAT jestermaxxing W");
      System.out.println("Rizz drip washed ratio");
      System.out.println("sigma balls looksmaxxing caught in 4K");
      System.out.println("UWU aura be yappin' bruh");
      System.out.println("SYBAU sussy baka is joever KYS");
      System.out.println("Skibidi aura slapsno shit");
      System.out.println("Cringe GOAT SDIYBTing bruh");
      System.out.println("goofy ahh drip is joever cooked");
      System.out.println("SYBAU sussy baka slapsno cap");
      System.out.println("Rizz 67 tweaking ratio");
      System.out.println("Rizz GOAT simp cooked");
      System.out.println("Zesty aura rage-baiting caught in 4K");
      System.out.println("Gigachad sussy baka locked in KYS");
      System.out.println("Zesty bussi touching grass no shit");
      System.out.println("goofy ahh bussi SDIYBTing bruh");
      System.out.println("Zesty bussi vibe check ratio");
      System.out.println("SYBAU aura be yappin' bruh");
      System.out.println("sigma 67 rage-baiting caught in 4K");
      System.out.println("Zesty fire gooning ratio");
      System.out.println("bussin' gyatt slapsW");
      System.out.println("UWU bussi tweaking caught in 4K");
      System.out.println("Omega drip fanum taxed moged ");
      System.out.println("Omega dih washed bruh");
      System.out.println("Gigachad dih gooning twin");
      System.out.println("goofy ahh 67 tweaking bruh");
      System.out.println("goofy ahh aura looksmaxxing L");
      System.out.println("Rizz aura tweaking cooked");
      System.out.println("sigma GOAT is joever no shit");
      System.out.println("Cringe dih be yappin' cooked");
      System.out.println("goofy ahh bussi touching grass frfr");
      System.out.println("Rizz GOAT fanum taxed W");
      System.out.println("sigma gyatt is joever caught in 4K");
      System.out.println("Zesty balls be yappin' KYS");
      System.out.println("sigma drip SDIYBTing caught in 4K");
      System.out.println("Skibidi drip rage-baiting moged ");
      System.out.println("UWU bussi rage-baiting ratio");
  }
}